development:
  adapter: postgresql
  encoding: unicode
  database: davidchau_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: davidchau_test
  pool: 5
  username: postgres
  password: postgres